# Generated by Django 3.2.9 on 2021-11-13 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('copytter', '0001_initial'), ('copytter', '0002_entry_follow_user'), ('copytter', '0003_auto_20211113_1627'), ('copytter', '0004_alter_user_status'), ('copytter', '0005_auto_20211113_2318'), ('copytter', '0006_auto_20211114_0009'), ('copytter', '0007_auto_20211114_0013'), ('copytter', '0008_auto_20211114_0015'), ('copytter', '0009_auto_20211114_0016'), ('copytter', '0010_auto_20211114_0018'), ('copytter', '0011_auto_20211114_0021'), ('copytter', '0012_auto_20211114_0025'), ('copytter', '0013_auto_20211114_0026'), ('copytter', '0014_auto_20211114_0028')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('icon_pass', models.ImageField(blank=True, upload_to='images/')),
                ('profile_message', models.TextField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('public', '一般'), ('block', '凍結'), ('machine', 'BOT'), ('official', '公式'), ('close', '非公開')], default='publish', max_length=10)),
                ('sensitive_entry', models.BooleanField(default=False)),
                ('follow_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile_user_id', models.CharField(default='3X9GUKzHuT', max_length=32, unique=True)),
                ('profile_first_registed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('public', '公開中'), ('close', '非公開'), ('machine', 'BOT')], default='draft', max_length=8)),
                ('relation_id', models.CharField(max_length=8)),
                ('like_count', models.IntegerField(default=0)),
                ('media_close', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relation_cont', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
