# Generated by Django 3.2.9 on 2021-11-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0001_squashed_0014_auto_20211114_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='jGJPtgoCBp', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('block', '凍結'), ('machine', 'BOT'), ('public', '一般'), ('official', '公式'), ('close', '非公開')], default='publish', max_length=10),
        ),
    ]
