# Generated by Django 3.2.9 on 2021-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0003_auto_20211125_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='0Jaje0tzuw', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('official', '公式'), ('public', '一般'), ('close', '非公開'), ('machine', 'BOT'), ('block', '凍結')], default='publish', max_length=10),
        ),
    ]
