# Generated by Django 3.2.9 on 2021-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0003_auto_20211114_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='Q7h5n0qVqC', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('official', '公式'), ('block', '凍結'), ('machine', 'BOT'), ('public', '一般'), ('close', '非公開')], default='publish', max_length=10),
        ),
    ]
