# Generated by Django 3.2.9 on 2021-11-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0004_auto_20211125_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='LMmcJ3vEQc', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('public', '一般'), ('machine', 'BOT'), ('close', '非公開'), ('official', '公式'), ('block', '凍結')], default='publish', max_length=10),
        ),
    ]
