# Generated by Django 3.2.9 on 2021-11-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0004_auto_20211114_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='L56rewKtUW', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('block', '凍結'), ('public', '一般'), ('close', '非公開'), ('official', '公式'), ('machine', 'BOT')], default='publish', max_length=10),
        ),
    ]
