# Generated by Django 3.2.9 on 2021-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0005_auto_20211114_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='5SkmRCsJQD', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('close', '非公開'), ('official', '公式'), ('machine', 'BOT'), ('public', '一般'), ('block', '凍結')], default='publish', max_length=10),
        ),
    ]
