# Generated by Django 3.2.9 on 2021-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0006_auto_20211125_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='icon_pass',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='BrOuDNKuDy', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('machine', 'BOT'), ('public', '一般'), ('official', '公式'), ('block', '凍結'), ('close', '非公開')], default='public', max_length=10),
        ),
    ]
