# Generated by Django 3.2.9 on 2021-11-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0006_auto_20211114_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='Mre7VcsK21', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('public', '一般'), ('block', '凍結'), ('close', '非公開'), ('official', '公式'), ('machine', 'BOT')], default='publish', max_length=10),
        ),
    ]
