# Generated by Django 3.2.9 on 2021-11-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0007_auto_20211114_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='0o1I6JqgQX', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('machine', 'BOT'), ('official', '公式'), ('public', '一般'), ('close', '非公開'), ('block', '凍結')], default='publish', max_length=10),
        ),
    ]
