# Generated by Django 3.2.9 on 2021-11-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0007_auto_20211127_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon_pass',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='OtTe1HIF3E', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('block', '凍結'), ('public', '一般'), ('official', '公式'), ('machine', 'BOT'), ('close', '非公開')], default='public', max_length=10),
        ),
    ]
