# Generated by Django 3.2.9 on 2021-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0008_auto_20211114_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='H0YmRMNhjL', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('close', '非公開'), ('public', '一般'), ('official', '公式'), ('machine', 'BOT'), ('block', '凍結')], default='publish', max_length=10),
        ),
    ]
