# Generated by Django 3.2.9 on 2021-11-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0009_auto_20211114_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='DueZSzTc9h', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('block', '凍結'), ('official', '公式'), ('public', '一般'), ('machine', 'BOT'), ('close', '非公開')], default='publish', max_length=10),
        ),
    ]
