# Generated by Django 3.2.9 on 2021-11-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytter', '0009_auto_20211127_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_user_id',
            field=models.CharField(default='OrpkujB2gW', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('close', '非公開'), ('block', '凍結'), ('public', '一般'), ('machine', 'BOT'), ('official', '公式')], default='public', max_length=10),
        ),
    ]
